export const position = ["QB", "RB", "WR", "TE", "DE", "DT", "LB", "CB", "S"];
export const team = [
  { abr: "ARI", name: " Arizona Cardinals" },
  { abr: "ATL", name: "Atlanta Falcons" },
  { abr: "BAL", name: "Baltimore Ravens" },
  { abr: "BUF", name: "Buffalo Bills" },
  { abr: "CAR", name: "Carolina Panthers" },
  { abr: "CHI", name: "Chicago Bears" },
  { abr: "CIN", name: "Cincinnati Bengals" },
  { abr: "CLE", name: "Cleveland Browns" },
  { abr: "DAL", name: "Dallas Cowboys" },
  { abr: "DEN", name: "Denver Broncos" },
  { abr: "DET", name: "Detroit Lions" },
  { abr: "GB", name: "Green Bay Packers" },
  { abr: "HOU", name: "Houston Texans" },
  { abr: "IND", name: "Indianapolis Colts" },
  { abr: "JAX", name: "Jacksonville Jaguars" },
  { abr: "KC", name: "Kansas City Chiefs" },
  { abr: "LV", name: "Las Vegas Raiders" },
  { abr: "MIA", name: "Miami Dolphins" },
  { abr: "MIN", name: " Minnesota Vikings" },
  { abr: "NE", name: "New England Patriots" },
  { abr: "NO", name: "New Orleans Saints" },
  { abr: "NYG", name: "New York Giants" },
  { abr: "NYJ", name: "New York Jets" },
  { abr: "PHI", name: "Philadelphia Eagles" },
  { abr: "PIT", name: "Pittsburgh Steelers" },
  { abr: "SD", name: "San Diego Chargers" },
  { abr: "SEA", name: "Seattle Seahawks" },
  { abr: "SF", name: "San Francisco 49ers" },
  { abr: "STL", name: "Saint Louis Rams" },
  { abr: "TB", name: "Tampa Bay Buccaneers" },
  { abr: "TEN", name: "Tennessee Titans" },
  { abr: "WAS", name: "Washington Football Team" },
];
export const fantasyScoring = [
  { abr: "STD", name: "Standard scoring" },
  { abr: "Half – PPR", name: "Half Point Per Reception" },
  {
    abr: "0.5 PPR - TEP",
    name: "Half Point Per Reception - Tight end Premium",
  },
  { abr: "PPR", name: "Points Per Reception" },
  { abr: "PPR -TEP", name: "Points Per Reception - Tight end Premium" },
  { abr: "SFB", name: "Scott Fish Bowl" },
  { abr: "IDP", name: " Individual Defense Player" },
];
export const preSeason = ["Week 1", "Week 2", " Week 3", "Week 4"];
export const regularSeason = [
  "Week 1",
  "Week 2",
  "Week 3",
  "Week 4",
  "Week 5",
  "Week 6",
  "Week 7",
  "Week 8",
  "Week 9",
  "Week 10",
  "Week 11",
  "Week 12",
  "Week 13",
  "Week 14",
  "Week 15",
  "Week 16",
  "Week 17",
  "Week 18",
];
export const postSeason = [
  "WC-Wildcard",
  " D-Divisional",
  "C- Championship",
  "SB – Super Bowl",
  // { abr: "WC", name: "Wildcard" },
  // { abr: "D", name: "Divisional" },
  // { abr: "C", name: "Championship" },
  // { abr: "SB", name: "Super Bowl" },
];
